# Auto-labeling configuration for Pull Requests
# Format for actions/labeler@v5

# Projects
project/core:
  - changed-files:
    - any-glob-to-any-file: 'CheapUpscaler.Core/**/*'

project/blazor:
  - changed-files:
    - any-glob-to-any-file: 'CheapUpscaler.Blazor/**/*'

# Areas
area/ui:
  - changed-files:
    - any-glob-to-any-file:
      - '**/Components/**/*'
      - '**/*.razor'

area/services:
  - changed-files:
    - any-glob-to-any-file: '**/Services/**/*'

area/models:
  - changed-files:
    - any-glob-to-any-file: '**/Models/**/*'

area/data:
  - changed-files:
    - any-glob-to-any-file: '**/Data/**/*'

area/ai-upscaling:
  - changed-files:
    - any-glob-to-any-file:
      - '**/RealCUGAN/**/*'
      - '**/RealESRGAN/**/*'

area/frame-interpolation:
  - changed-files:
    - any-glob-to-any-file: '**/RIFE/**/*'

area/video-processing:
  - changed-files:
    - any-glob-to-any-file:
      - '**/VapourSynth/**/*'
      - '**/Upscaling/**/*'

area/queue:
  - changed-files:
    - any-glob-to-any-file:
      - '**/UpscaleQueue*'
      - '**/BackgroundTaskQueue*'

# File types
type/documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

type/config:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.json'
      - '**/*.config'

type/build:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.csproj'
      - '**/*.slnx'
      - '**/*.sln'
      - '.github/**/*'

# Changes
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - '**/packages.lock.json'
      - '**/*.csproj'
