// <auto-generated />
using System;
using CheapUpscaler.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheapUpscaler.Shared.Migrations
{
    [DbContext(typeof(UpscaleJobDbContext))]
    [Migration("20260804200908_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CheapUpscaler.Shared.Data.UpscaleJobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentFrame")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorStackTrace")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<long?>("EstimatedTimeRemainingTicks")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OutputFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OutputFps")
                        .HasColumnType("REAL");

                    b.Property<int?>("OutputHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputWidth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ProgressPercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SourceDurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SourceFps")
                        .HasColumnType("REAL");

                    b.Property<int?>("SourceHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceVideoPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceWidth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalFrames")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UpscaleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
